baseURL = "http://http://hugo-s6e5.s3-wesite-us-east-1.amazonaws.com//"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "ananke"

[[deployment.targets]]# An arbitrary name for this target.
name="awsbucket"
URL="s3://hugo-s6e5/?region=us-east-1"